roles/adguardhome/defaults/main.yml, roles/adguardhome/tasks/main.yml, roles/adguardhome/templates/AdGuardHome.yaml.js2, roles/mkvtoolnix/defaults/main.yml, roles/mkvtoolnix/tasks/main.yml, sandbox.yml
Testing two roles from sevos community PRs.
Both tested and install.
Check with @sevospl first before merging.
=> initial branch from sevos community PRS

README.md, defaults/settings.yml.default, roles/notifiarr/defaults/main.yml, roles/notifiarr/tasks/main.yml, roles/notifiarr/tasks/subtasks/settings.yml, roles/notifiarr/templates/notifiarr.conf.j2, sandbox.yml
Add Notifiarr App as per issue #6
=> Feat notifiarr

roles/mkvtoolnix/defaults/main.yml, roles/plexwrapped/defaults/main.yml, roles/plexwrapped/tasks/main.yml, sandbox.yml
=> Feat plexwrapped

roles/nabarr/defaults/main.yml, roles/nabarr/files/config.yml.sample, roles/nabarr/tasks/main.yml, roles/nabarr/tasks/subtasks/settings.yml, sandbox.yml
New role nabarr
Requested in #17 
Create sample config but does not auto fill  parameters.
=> Feat nabarr

roles/tdarr/defaults/main.yml, roles/tdarr/tasks/main.yml, roles/tdarr_node/defaults/main.yml, roles/tdarr_node/tasks/main.yml, sandbox.yml
=> Feat tdarr

roles/xbackbone/defaults/main.yml, roles/xbackbone/tasks/main.yml, sandbox.yml
=> Add xbackbone role

roles/rocketchat/defaults/main.yml, roles/rocketchat/tasks/main.yml, sandbox.yml
=> Add Rocketchat role

defaults/settings.yml.default, roles/sarotate/defaults/main.yml, roles/sarotate/tasks/main.yml, roles/sarotate/tasks/subtasks/config.yml, roles/sarotate/templates/config.yaml.j2, roles/sarotate/templates/sarotate.service.j2, sandbox.yml
Added a role for sarotate. user input required for remotes and service accounts folder path. rest are optional with default values present if not entered by user according to default config and default saltbox install
Tested in my server
=> SARotate Role

roles/a_train/tasks/subtasks/config.yml, roles/sarotate/tasks/subtasks/config.yml
For new roles please include a brief description of what this app does, or what the purpose of this role is. Include a link to the docker container used, the projects home page and a link to the documentation if it exists.
For existing roles, please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
=> removing lower case forced in remotes

roles/sarotate/tasks/main.yml
For new roles please include a brief description of what this app does, or what the purpose of this role is. Include a link to the docker container used, the projects home page and a link to the documentation if it exists.
For existing roles, please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
=> correcting a few conditionals

roles/privatebin/defaults/main.yml, roles/privatebin/tasks/main.yml, sandbox.yml
PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data.
It's privacy-preserving and encrypted-by-default.
Project: https://privatebin.info/
Container: https://hub.docker.com/r/privatebin/nginx-fpm-alpine
Wiki: https://github.com/PrivateBin/PrivateBin/wiki
I have tested it on my saltbox setup multiple time (delete + install) and everything work without issues.
It's my first role, so tell me if something is not correct.
Thanks
- [ ✅] ```sb install sandbox-privatebin```
- [ ✅] Check that the service work at privatebin.domain.com
=> Add Private Bin

roles/plextraktsync/tasks/subtasks/post-install/main.yml, roles/plextraktsync/tasks/subtasks/pre-install/main.yml
Minor textual changes following recent merge: https://github.com/Taxel/PlexTraktSync/pull/852 (migrates config.json to config.yml)
I'm working on documentation for the role. PR soon.
=> PlexTraktSync: minor update

roles/whisparr/defaults/main.yml, roles/whisparr/tasks/main2.yml
Add support for theme.park to Whisparr role
~~Awaiting merging of this PR https://github.com/GilbN/theme.park/pull/378~~
=> Whisparr: Add theme.park

roles/a_train/tasks/main.yml, roles/a_train/tasks/subtasks/config.yml, roles/a_train/tasks/subtasks/settings.yml
- [ -] I have now checked three boxes without reading any of the text
=> atrain fqcn linting

roles/watchtower/tasks/main.yml, roles/whisparr/defaults/main.yml, roles/wordpress/tasks/main.yml, roles/wrapperr/tasks/main.yml, roles/xbackbone/tasks/main.yml, roles/xteve/tasks/main.yml, roles/yacht/tasks/main.yml, roles/znc/tasks/main.yml
=> FQCN W - Z

roles/audiobookshelf/defaults/main.yml, roles/audiobookshelf/tasks/main.yml, sandbox.yml
App request via #70 Audiobookshelf
Install in a testing server, install on a working server and tested to connect with android app.
No tests with iOS as I do not have access.
=> Audiobookshelf

roles/recyclarr/defaults/main.yml
Making this role consistent with the changes in https://github.com/saltyorg/Sandbox/commit/5fd0719d0af047ef4fe9ecc9c1fcc553fdeb8a06
=> Remove pointless empty array declaration

roles/sabthrottle/defaults/main.yml, roles/sabthrottle/tasks/main.yml, roles/sabthrottle/tasks/subtasks/pre-install.yml, roles/sabthrottle/templates/config.json.j2, sandbox.yml
https://hub.docker.com/repository/docker/8a8al00ey/sabthrottle
https://github.com/8a8al00ey/sabthrottle.git
This is almost identical to nzbthrottle except it works with SABnzbd instead. It will also auto populate plex url and auth token. 
Ran the role on my machine.
=> Add sabthrottle

roles/tandoor/defaults/main.yml, roles/tandoor/tasks/main.yml, sandbox.yml
https://github.com/TandoorRecipes/recipes
Closes #103
=> Tandoor: New Role

roles/tandoor/defaults/main.yml
=> Minor formatting fixes

roles/plex_credits_detect/defaults/main.yml, roles/plex_credits_detect/tasks/main.yml, roles/plex_credits_detect/templates/fingerprint.ini.j2, sandbox.yml
https://github.com/cjmanca/plex-credits-detect
=> Plex-Credits-Detect: New Role

roles/olivetin/defaults/main.yml, roles/olivetin/tasks/main.yml, roles/olivetin/templates/config.yaml.j2, sandbox.yml
=> OliveTin: New Role

roles/cherry/defaults/main.yml, roles/cherry/tasks/main.yml, sandbox.yml
**Cherry** is a bookmark service.
- It's open source. the code of Cherry service, the browser extension and also this website are all available on GitHub.
- It's self-hostable. Your data in in your own hands. It's also easy to deploy, a Docker image is provided. It's using SQLite, management and backup is a breeze.
- It has a simple UI. But you got all the features you want for a bookmark service. Tags, groups, full text search and browser extensions.
Docs: https://cherry.haishan.me/
=> feat(role): add cherry

roles/plex_utills/defaults/main.yml
I just realized that further to a modification in plex-utills , we need to update the default volumes.
Tested successfully on my saltbox instance.
=> Plex-utills : Correction in the Volume path

roles/n8n/defaults/main.yml, roles/n8n/tasks/main.yml, sandbox.yml
n8n is an extendable workflow automation tool. With a [fair-code](http://faircode.io/) distribution model, n8n will always have visible source code, be available to self-host, and allow you to add your own custom functions, logic and apps. n8n's node-based approach makes it highly versatile, enabling you to connect anything to everything.
Demo: https://www.youtube.com/watch?v=RpjQTGKm-ok
Docs: https://docs.n8n.io/
Integrations: https://n8n.io/integrations
More infos: https://n8n.io/
=> feat(role): add n8n (#142)

roles/wikijs/defaults/main.yml, roles/wikijs/tasks/main.yml, sandbox.yml
Wiki.js is an open source project that has been made possible due to the generous contributions by community [backers](https://js.wiki/about).
Demo: https://docs.requarks.io/demo
Docs: https://docs.requarks.io/
More infos: https://js.wiki/
=> feat(role): add wikijs (#118)

roles/koel/defaults/main.yml, roles/koel/tasks/main.yml, sandbox.yml
n8n is an extendable workflow automation tool. With a [fair-code](http://faircode.io/) distribution model, n8n will always have visible source code, be available to self-host, and allow you to add your own custom functions, logic and apps. n8n's node-based approach makes it highly versatile, enabling you to connect anything to everything.
App: https://koel.dev/
Docker: https://github.com/koel/docker
=> feat(role): add koel

roles/heimdall/defaults/main.yml
=> feat(heimdall): switch to SSO auth and add healthcheck (close #153)

roles/lunasea/defaults/main.yml, roles/lunasea/tasks/main.yml, sandbox.yml
LunaSea is a fully featured, open source self-hosted controller focused on giving you a seamless experience between all of your self-hosted media software remotely on your devices.
Home: https://www.lunasea.app
Github: https://github.com/JagandeepBrar/LunaSea
Docs: https://www.lunasea.app/docs
=> feat(role): add lunasea

roles/coder/defaults/main.yml
=> fix(coder): add missing .local path (close #145)

roles/gaps/defaults/main.yml, roles/gaps/tasks/main.yml, sandbox.yml
Gaps searches through your Plex Server for all movies, then queries for known movies in the same collection. If those movies don't exist in your library, Gaps will recommend getting those movies, legally of course.
Github: https://github.com/JasonHHouse/gaps
=> feat(role): add gaps (close #124)

defaults/settings.yml.default
Remove comments from settings file, forgot to PR, need to compare before merge to make sure there have been no additions since edits made.
=> remove comments from settings

roles/duplicati/defaults/main.yml, roles/duplicati/tasks/main.yml
Duplicati is an open source backup application, which runs on your local machine, and encrypts data prior to uploading it. The user interface is web-based and allows you to control all the options offered by Duplicati, from a simple and intuitive interface.
run locally
=> add duplicati

roles/elasticsearch/defaults/main.yml, roles/elasticsearch/tasks/main.yml, roles/tubearchivist/defaults/main.yml, roles/tubearchivist/tasks/main.yml, sandbox.yml
Once your YouTube video collection grows, it becomes hard to search and find a specific video. That's where Tube Archivist comes in: By indexing your video collection with metadata from YouTube, you can organize, search and enjoy your archived YouTube videos without hassle offline through a convenient web interface.
- **Homepage:** https://www.tubearchivist.com/
- **Github Repository:** https://github.com/tubearchivist/tubearchivist
- **Docker Github Repository:** https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml
- **Documentation:** https://github.com/tubearchivist/tubearchivist/wiki
Inc. a new sub-role, elasticsearch.
=> feat(role): add tubearchivist (inc. elasticsearch)

roles/plextraktsync/defaults/main.yml, roles/plextraktsync/tasks/main.yml, roles/plextraktsync/tasks/subtasks/pre-install/main.yml, roles/plextraktsync/templates/env.j2
- remove `user` docker parameter to avoid pipx error
- add app data chown task
- some streamlining
=> PlexTraktSync fix

roles/phpmyadmin/defaults/main.yml, roles/phpmyadmin/tasks/main.yml, sandbox.yml
A web interface for MySQL and MariaDB.
- **Homepage:** https://www.phpmyadmin.net
- **Github Repository:** https://github.com/phpmyadmin/phpmyadmin
- **Docker Github Repository:** https://hub.docker.com/_/phpmyadmin
- **Documentation:** https://docs.phpmyadmin.net/
=> feat(role): add phpmyadmin

README.md, roles/homarr/defaults/main.yml, roles/homarr/tasks/main.yml, roles/homeassistant/defaults/main.yml, roles/homeassistant/tasks/main.yml, roles/homeassistant/templates/configuration.yaml.j2, sandbox.yml
Homarr is a simple and lightweight homepage for your server, that helps you easily access all of your services in one place.
It integrates with the services you use to display information on the homepage (E.g. Show upcoming Sonarr/Radarr releases).
[Homarr](https://github.com/ajnart/homarr)
[Homarr Docs](https://homarr.dev/docs/about)
Refer to issue #179 
I installed it on my home server and my remote. It connected fine to docker, displays the containers, allows for creating service based on the container. 
I need help maybe? with the healthcheck section of the role. It causes the web ui to not load. It doesn't show any errors in logs, so I commented it out. @JigSawFr 
What am I missing? Otherwise, it looks great and works like a charm so far.
=> Add homarr to sandbox

roles/tandoor/defaults/main.yml
Added Authelia SSO to the tandoor application role.
**Impact**: Security
**Experienced**: Tandoor is currently only secured behind the built in authentication method. This is not consistent with other roles. We have an SSO that is updated with uniform security updates. 
**Expected**: Tandoor should be secured behind Authelia SSO.
=> feat: tandoor: adding sso to app

roles/uptime_kuma/defaults/main.yml, roles/uptime_kuma/tasks/main.yml
=> feat(uptime-kuma): use PUID/PGID & protect with authelia by default

roles/adguardhome/defaults/main.yml, roles/adguardhome/tasks/main.yml, roles/minecraft/defaults/main.yml, roles/uptime_kuma/defaults/main.yml
=> Traefik3 Adguard update

roles/autobrr/tasks/main.yml
autobrr directory for the register ansible task was `autobbr` instead of `autobrr`
=> Update autobrr role tasks main.yml

roles/krusader/defaults/main.yml, roles/krusader/tasks/main.yml, sandbox.yml
Container and Documentation: https://hub.docker.com/r/binhex/arch-krusader
Project: https://krusader.org/
I'll add documentation to the docs repo.
=> Added krusader role

roles/mqtt/defaults/main.yml, roles/mqtt/tasks/main.yml
Updated defaults/main.yml, removed PUID and GUID as the container doesn't support it. Removed exposed ports from role. Added docker user mapping with uid:gid. 
Updated tasks/main.yml, removed chown task as its no longer needed with correct user mapping.
=> Update mqtt defaults/main.yml

roles/threadfin/defaults/main.yml, roles/threadfin/tasks/main.yml, sandbox.yml
Based on xTeve. Includes bug fixes and is actively developed. See https://github.com/Threadfin/Threadfin for source.
Tested on my production server with Plex and Jellyfin.
=> Threadfin: New role

roles/firefox/defaults/main.yml, roles/firefox/tasks/main.yml, roles/firefox/templates/env.j2, sandbox.yml
- https://github.com/saltyorg/Sandbox/issues/264 
- https://github.com/jlesage/docker-firefox
=> feat(role): add firefox

defaults/settings.yml.default, roles/foundry/defaults/main.yml, roles/foundry/tasks/main.yml, sandbox.yml
This is a role for foundryVTT
Project Homepage : https://foundryvtt.com/
Documentation : https://foundryvtt.com/kb/
Docker image : https://hub.docker.com/r/felddy/foundryvtt
Configure the settings : 
foundry:
user: your_foundryvtt_username
pass: your_foundryvtt_password
app_key: your_foundryvtt_license
Create a Foundry Directory in your Media folder
Install role
Enjoy
- [X ] I tested this on my server setup and it's working fine
=> Adding foundry role

roles/watchtower/defaults/main.yml
=> fix(watchtower): bad file path concatenation

roles/tubearchivist/tasks/main.yml
This is to match the tubearchivist compose for elasticsearch https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml Hope I did it right
=> Match Tubearchivist compose

roles/code_server/defaults/main.yml
Updating code_server linting. I noticed it wasn't properly salty linted.
=> Update code_server Lint

roles/immich/defaults/main.yml
Update the postgres version following the maintainers directions. When I tested on my own container (non image genius/ all in one) I had to restart both postgres and immich once. Before I restarted, it didn't want to sync for some reason or another.
=> Update Immich | Defaults | main.yml

roles/openobserve/defaults/main.yml, roles/openobserve/tasks/main.yml, sandbox.yml
> Full stack observability 
Website: https://openobserve.ai
Documentation: https://openobserve.ai/docs/
Repository: https://github.com/openobserve/openobserve
Container: public.ecr.aws/zinclabs/openobserve
Yet another selfhosted logs/metrics/traces tool.
I've been running it on my own server by installing it through this specific role from my own repo/branch. Haven't run into any issues as of yet.
=> feat(role): add openobserve

roles/semaphoreui/defaults/main.yml, roles/semaphoreui/tasks/main.yml, sandbox.yml
Semaphore is a modern UI for Ansible, Terraform/OpenTofu, Bash and Pulumi. It lets you easily run Ansible playbooks, get notifications about fails, control access to deployment system.
If your project has grown and deploying from the terminal is no longer for you then Semaphore UI is what you need.
- Operating System
- Install Type
=> App Request: Semaphore

roles/maybe_finance/defaults/main.yml, roles/maybe_finance/tasks/main.yml, sandbox.yml
This app is a self-hosted personal finance dashboard, along the lines of Personal Capital.
- [Project home page](https://maybefinance.com/)
- [Project docs](https://github.com/maybe-finance/maybe)
- [Docker container](https://ghcr.io/maybe-finance/maybe)
PR for docs update: https://github.com/saltyorg/docs/pull/334
Closes https://github.com/saltyorg/Sandbox/issues/388
=> Maybe Finance Role

roles/profilarr/defaults/main.yml, roles/profilarr/tasks/main.yml, sandbox.yml
- https://github.com/Dictionarry-Hub/profilarr
=> feat(role): add profilarr

roles/profilarr/defaults/main.yml
=> fix(profilarr): add user mapping

roles/watchstate/defaults/main.yml
- Add automatic web UI access to backend
- Refactor Docker envs for simpler inventory overriding
- Update API passthrough to the new endpoint they use
=> feat(watchstate): update

roles/maintainerr/defaults/main.yml
- maintainerr has never had themepark support
- unused path vars
- unused [envs](https://docs.maintainerr.info/latest/Installation/#environment-variables)
=> fix(maintainerr): clean up overseerr role copypasta leftovers
