- defaults/settings.yml.default
- roles/plextraktsync/defaults/main.yml
- roles/plextraktsync/tasks/main.yml
- sandbox.yml
Official docker image **ghcr.io/taxel/plextraktsync** with **watch** command appended so that it runs as a server and scrobbles plays. 
Library sync automation not included (maybe we can work that in later), but can be done by adding `docker exec -it plextraktsync python3 -m plextraktsync sync` to crontab, for example.
The container would not stay up without a valid Plex server to connect to, so I set the envs to login to the local Plex server by default, with override settings in _settings.yml_.
I tried my hand at customizing the tag feed with some eye-catching setup instructions, hoping they will be noticed. ¯\_(シ)_/¯
> Role for PlexTraktSync

- defaults/settings.yml.default
- roles/plextraktsync/defaults/main.yml
- roles/plextraktsync/tasks/main.yml
- roles/plextraktsync/tasks/subtasks/post-install/main.yml
- roles/plextraktsync/tasks/subtasks/pre-install/main.yml
Take two...
- Plex envs are now fully applied with the .env file instead of Docker parameters
- More reliable way to retrieve a valid Plex username to use by default
- Added another post-install message
- Reinstall will no longer get stuck on "Remove existing Docker container" past 10 seconds
- Settings.yml block removed, since any change in setup should be done via the built-in interactive script
> PlexTraktSync: Rework

- defaults/settings.yml.default
- roles/transmissionvpn/defaults/main.yml
- roles/transmissionvpn/tasks/main.yml
- sandbox.yml
Adapted from the cloudbox community role. [Container](https://hub.docker.com/r/haugene/transmission-openvpn/) and [docs](https://haugene.github.io/docker-transmission-openvpn/)
Recently migrated from cloudbox and tested on my new saltbox instance.
> Add transmissionvpn role

- defaults/settings.yml.default
- roles/recyclarr/defaults/main.yml
- roles/recyclarr/tasks/main.yml
- sandbox.yml
Recyclarr automatically synchronizes recommended settings from TRaSH guides to your Sonarr/Radarr instances.
* Docker container: [ghcr.io/recyclarr/recyclarr](https://ghcr.io/recyclarr/recyclarr)
* Project homepage: [github.com/recyclarr/recyclarr](https://github.com/recyclarr/recyclarr)
* Configuration reference: [github.com/recyclarr/recyclarr/wiki/Configuration-Reference](https://github.com/recyclarr/recyclarr/wiki/Configuration-Reference)
* Configuration examples: [github.com/recyclarr/recyclarr/wiki/Configuration-Examples](https://github.com/recyclarr/recyclarr/wiki/Configuration-Examples)
* Documentation wiki for docker image: [github.com/recyclarr/recyclarr/wiki/Docker](https://github.com/recyclarr/recyclarr/wiki/Docker)
I ran the role on my saltbox server and tested the following: …
> Recyclarr: New Role

- roles/deemix/defaults/main.yml
- This adds the default sso middleware for deemix.
For new roles please include a brief description of what this app does, or what the purpose of this role is. Include a link to the docker container used, the projects home page and a link to the documentation if it exists.
It would be greatly appreciated if you create a sandbox documentation page yourself and do a PR into the [docs repo](https://github.com/saltyorg/docs).  You, as the person creating the role, have presumably used the thing and are presumably familiar with any setup steps required.  Anyone else here would need to research that.
For existing roles, please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this …
> Update deemix to add authelia auth

- roles/speedtest/defaults/main.yml
Add theme.park to Speedtest role using Docker Mod method.
> Speedtest: Add theme.park support

- roles/alltube/defaults/main.yml
Updates All Tube's default main.yml to configure Traefik with Authelia's middleware. This prevents users from accessing the alltube URL without first authenticated with Authelia if it's configured.
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.
```
Sunday 24 July 2022  22:19:37 +0200 (0:00:05.292)       0:00:30.869 *********** 
=============================================================================== 
alltube : Download alltube config example ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Add Authelia SSO support for AllTube

- roles/tandoor/defaults/main.yml
Debug mode is enabled by default. This sets a docker env of DEBUG=0 to disable it. 
Tested on my production installation. Confirmed that it disabled debug mode.
> Set DEBUG env to 0

- roles/tandoor/defaults/main.yml
Added docker env `GUNICORN_MEDIA: 1` to explicitly enable Gunicorn to serve media files. This is currently the default but the dev has stated that it will change at some point.
Note: The dev recommends running a separate webserver for media files because of performance issues with Gunicorn. For small installs with few users it should be fine. But it might be worth looking at integrating an nginx container, similar to the invoiceninja role.
Tested on my production install of Tandoor.
> Added env to explicitly enable Gunicorn for media files

- roles/tandoor/defaults/main.yml
The Tandoor docker image expects a root user. When using the SB `uid` and `pid` for `tandoor_docker_user` some functionality breaks. In particular, the Space Settings are completely inaccessible. Without this, it's impossible to invite users.
Removing `tandoor_docker_user` restores the functionality. The two directories that are created (`mediafiles` and `staticfiles`) will be still be owned by the SB user but any content added to those directories by the container will be owned by root. Since these files aren't typically edited directly by the user, this shouldn't be a significant problem.
The dev has expressed some interest in fixing this but it's not a priority. If a fix is ever implemented, we can revert to a non-root user.
Tested on my production installation. Created new recipes, …
> Removed tandoor_docker_user, container expects root user

- roles/calibre_web/defaults/main.yml
Calibre-web will create thumbnails inside the container unless the `CACHE_DIR` environment variable is set a bind volume. This adds the docker env and specifies a cache directory in the calibre-web path.
Tested on my production instance of calibre-web.
> Add persistent thumbnail cache directory

- roles/recyclarr/defaults/main.yml
Remove PUID/PGID from role as Recyclarr has switched to a rootless container and these envs will break new installs.
Tested on my production server using the `edge` tag for Recyclarr. Confirmed it's working with `latest` tag now that it's been released.
> Update for Recyclarr rootless container

- roles/qbittorrentvpn/defaults/main.yml
- roles/qbittorrentvpn/tasks/main.yml
- roles/qbittorrentvpn/tasks/main2.yml
- roles/qbittorrentvpn/tasks/subtasks/post-install/main.yml
- roles/qbittorrentvpn/tasks/subtasks/post-install/settings/main.yml
- roles/qbittorrentvpn/tasks/subtasks/pre-install/main.yml
- sandbox.yml
Add a role for qbitttorrent with VPN from https://github.com/binhex/arch-qbittorrentvpn image.
Tested by include the role in the actual sandbox and run the tag by sb install sandbox-qbittorrentvpn
> feat: add qbittorrentvpn role

- roles/gotenberg/defaults/main.yml
- roles/gotenberg/tasks/main.yml
- roles/paperless_ngx/defaults/main.yml
- roles/paperless_ngx/tasks/main.yml
- roles/tika/defaults/main.yml
- roles/tika/tasks/main.yml
- sandbox.yml
**[Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx)** is a document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
[Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx) forked from [paperless-ng](https://github.com/jonaswinkler/paperless-ng) to continue the great work and distribute responsibility of supporting and advancing the project among a team of people.
Requested on https://github.com/saltyorg/Sandbox/issues/114
Completely tested and locked versions when needed.
> feat(role): add paperless-ngx (inc. gotenberg and tika) (#114)

- roles/minecraft_bedrock/defaults/main.yml
- roles/minecraft_bedrock/tasks/main.yml
- roles/settings/tasks/subtasks/finish.yml
- sandbox.yml
The existing **minecraft** role is only for the Java version of Minecraft. This role is for the Minecraft Bedrock Edition. (the multi-platform version)
For this server you need to expose a UDP port. You can access the server via the server IP and the default port 19132.
You can create a SRV entry that maps the server IP and UDP port to a subdomain.
_Is it possible to do this automatically via Ansible?_
- [itzg/minecraft-bedrock-server](https://hub.docker.com/r/itzg/minecraft-bedrock-server)
You can select a specific server version by overwriting this variable: `minecraft_bedrock_version`
Tested on my own server.
> minecraft-bedrock: New Role

- roles/photoprism/defaults/main.yml
- roles/photoprism/tasks/main.yml
- sandbox.yml
[Photoprism](https://photoprism.app/)® is an AI-Powered Photos App for the Decentralized Web. It makes use of the latest technologies to tag and find pictures automatically without getting in your way. You can run it at home, on a private server, or in the cloud. The docs are [here](https://docs.photoprism.app/)  
Compose file I based it off of. 
From their [GitHub](https://github.com/photoprism/photoprism/blob/develop/docker-compose.latest.yml)
```yaml
version: '3.5'
services:
photoprism-latest:
image: photoprism/photoprism:latest
security_opt:
- seccomp:unconfined
- apparmor:unconfined
ports:
- "2344:2342" # HTTP port (host:container)
labels:
- "traefik.enable=true"
- "traefik.http.services.latest.loadbalancer.server.port=2342"
- "traefik.http.routers.latest.entrypoints=websecure"
- …
```
> Photoprism

- roles/plextraktsync/templates/env.j2
A recent update in the project causes the Plex URL to default to `localhost` when `PLEX_BASEURL` is empty in the env file, which causes the container to fail. This works around the issue on a clean install.
> PlexTraktSync Fix

- roles/makemkv/defaults/main.yml
- roles/makemkv/tasks/main.yml
- sandbox.yml
MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere. MakeMKV is a format converter, otherwise called "transcoder". It converts the video clips from proprietary (and usually encrypted) disc into a set of MKV files, preserving most information but not changing it in any way. The MKV format can store multiple video/audio tracks with all meta-information and preserve chapters.
Home: https://www.makemkv.com
License purchase: https://www.makemkv.com/buy/
Docs: https://github.com/jlesage/docker-makemkv
> feat(role): add makemkv (#143)

- roles/rflood/defaults/main.yml
- Flood Download client
- Host: rflood
- Port: 3000
⚠️ Flood-UI API is not exposed externally (no auth behind).
> feat(rflood): switch to SSO auth and add healthcheck

- roles/puddletag/defaults/main.yml
- roles/puddletag/tasks/main.yml
- sandbox.yml
[Puddletag](https://docs.puddletag.net/) is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, Mp3tag. Unlike most taggers for GNU/Linux, it uses a spreadsheet-like layout so that all the tags you want to edit by hand are visible and easily editable.
I've tested it on my remote server, and my local/home server. 
[x] I did indeed tick a box.
> Add new role - Puddletag

- roles/aria2_ng/defaults/main.yml
- roles/aria2_ng/tasks/main.yml
- sandbox.yml
AriaNg is a modern web frontend making [aria2](https://github.com/aria2/aria2) easier to use. AriaNg is written in pure html & javascript, thus it does not need any compilers or runtime environment. You can just put AriaNg in your web server and open it in your browser. AriaNg uses responsive layout, and supports any desktop or mobile devices.
Github: https://github.com/hurlenko/aria2-ariang-docker
> feat(role): add aria2 + webui (close #2)

- roles/tvheadend/defaults/main.yml
- roles/tvheadend/tasks/main.yml
- sandbox.yml
Tvheadend is a TV streaming server and digital video recorder.
**It supports the following inputs:** DVB-C(2), DVB-T(2), DVB-S(2), ATSC, SAT>IP, HDHomeRun, IPTV, UDP, HTTP.
**It supports the following outputs:** HTTP, HTSP (own protocol), SAT>IP.
- **Homepage:** https://tvheadend.org/
- **Github Repository:** https://github.com/tvheadend/tvheadend
- **Docker Github Repository:** https://github.com/linuxserver/docker-tvheadend
- **Documentation:** https://tvheadend.org/projects/tvheadend/wiki
> feat(role): add tvheadend (close #31)

- roles/reposilite/defaults/main.yml
- roles/reposilite/tasks/main.yml
- sandbox.yml
Lightweight and easy-to-use repository manager for Maven based artifacts in JVM ecosystem.
Simple, extensible, scalable and self-hosted alternative to managers like Nexus, Archiva or Artifactory, with reduced resources consumption written in Kotlin 📦
https://reposilite.com/
It would be greatly appreciated if you create a sandbox documentation page yourself and do a PR into the [docs repo](https://github.com/saltyorg/docs).  You, as the person creating the role, have presumably used the thing and are presumably familiar with any setup steps required.  Anyone else here would need to research that.
Ran locally and tested login with specified user account/password in avd_setting.yml.
However, currently the docker image uses a hard-coded user/group id of 999:999, which may cause inconvenience …
> feat(role): add reposilite

- roles/plexshare/defaults/main.yml
- roles/plexshare/tasks/main.yml
- sandbox.yml
With this web application, anyone can create an account directly this app. Every body can add his PlexServer to the list. When you are connected by default you have access to all servers. But the admin can manage permission by user or by library like limit of number streaming, the quality and other
With only one interface and without plex.tv registration, everybody can have access to the libraries of all the servers you have registered.
- **Homepage:** https://chewbaka69.github.io/PlexShare/
- **Github Repository:** https://github.com/Chewbaka69/PlexShare
- **Docker Repository:** https://hub.docker.com/r/chewbaka/plexshare
- **Documentation:** https://github.com/Chewbaka69/PlexShare/wiki
Close #91
> feat(role): add plexshare (close #91)

- roles/docspell/defaults/main.yml
- roles/docspell/tasks/main.yml
- roles/solr/defaults/main.yml
- roles/solr/tasks/main.yml
- sandbox.yml
Docspell is a personal document organizer. Or sometimes called a "Document Management System" (DMS). You'll need a scanner to convert your papers into files. Docspell can then assist in organizing the resulting mess 😉. It can unify your files from scanners, emails and other sources. It is targeted for home use, i.e. families, households and also for smaller groups/companies.
You can associate tags, set correspondends and lots of other predefined and custom metadata. If your documents are associated with such meta data, you can quickly find them later using the search feature. But adding this manually is a tedious task. Docspell can help by suggesting correspondents, guessing tags or finding dates using machine learning. It can learn metadata from existing documents and find things using …
> feat(role): add docspell

- roles/homeassistant/defaults/main.yml
- roles/homeassistant/tasks/main.yml
- roles/homeassistant/templates/configuration.yaml.j2
- sandbox.yml
This PR is for Home assistant, it is open source home automation that puts local control and privacy first. Its powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server. Docker compose: 
```yaml
version: '3'
services:
homeassistant:
container_name: homeassistant
image: "lscr.io/linuxserver/homeassistant:stable"
volumes:
- /opt/homeassistant:/config
- /etc/localtime:/etc/localtime:ro
restart: unless-stopped
privileged: true
network_mode: host
```
It connects to LAN devices just fine, and is connectable after initial setup on lan IP, ie `192.168.1.xx:8123`
I will create the docs post haste!
I tested it many times on my local server, removing files and the directory multiple times. Salty gave me a hand with it a few times, figuring …
> feat(role): add homeassistant

- roles/tqm/tasks/main.yml
Added doc url to tqm [docs](https://docs.saltbox.dev/sandbox/apps/tqm/) in the fail message when config is not present in app directory.
> fix(tqm): add doc link to role

- roles/paperless_ngx/defaults/main.yml
Fix problems with mobile apps (iOS/Android) and usage of API.
Auto Login is replaced with Remote-User (bug encountered for API usage: https://github.com/paperless-ngx/paperless-ngx/issues/2075)
> fix(paperless): replace autologin with remote-user, add allowed hosts entries

- roles/mqtt/defaults/main.yml
- roles/mqtt/tasks/main.yml
- roles/mqtt/templates/mosquitto.conf.j2
- sandbox.yml
Adding a role for [mqtt](https://mqtt.org/) aka mosquitto, for use with homeassistant, node red, home bridge, and various other home based applications. 
MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas, etc.
I tested this pretty widely on my home server for a few months, and after a bit of tweaking the role, I think its ready to go. Obviously feel free to critique, or ask for closure of the pr if you think it unnecesarry. I have tested the role on my home …
> Add-mqtt role to sandbox

- roles/alternatrr/defaults/main.yml
Removes the now defunct /app subdirectory from the sonarr paths.
> Alternatrr: Fix old sonarr paths

- roles/xteve/defaults/main.yml
If channel logos are manually uploaded in xteve, or if image caching is enabled, clients can't access them because of Authelia. This enables API and adds `/data_images` as an endpoint to allow clients to access these without being blocked by the middleware.
> fix(xteve): enable API to allow uploaded channel logos

- roles/stash/defaults/main.yml
Stash is an organizer for porn. 
Since no sane person would want their personal porn collection accessible by anyone on the internet, the default should be to protect it with authelia.
Currently, the stash role isn't protected by authelia and the built-in auth isn't configured. This means that any rando can potentially take destructive actions like deleting stash's database or deleting files. 
This PR addresses this by adding authelia to `stash` in the defaults.
Since this is a one-line trivial edit I've not tested it.
> use authelia for `stash` by default

- roles/minecraft/defaults/main.yml
added `minecraft_dns_proxy: "false"` to DNS section of the role. For anyone that has Proxy enabled, this role will not work at all as is. I'm sure it would be fine if we added it as `minecraft_dns_proxy: "{{ dns.proxied }}"` as long as we update the docs?
> Update minecraft role main.yml

- roles/minecraft/tasks/main2.yml
After deploying the minecraft role several times, the CloudFlare proxy reactivated each time.
After checking the ansible task, I saw that the dns_proxy is not defined.
> Minecraft: fix dns_proxy

- roles/transmissionvpn/defaults/main.yml
Removing additional space as it causes "/etc/transmission/environment-variables.sh: line 20: export: `/opt/transmissionvpn': not a valid identifier" error
With the space, TransmissionVPN would continuously error out on "[2023-02-05 12:26:34.881] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server" meaning the container would not run.
> Remove additional space leading to crash of transmission-daemon

- roles/thelounge/defaults/main.yml
Adds api endpoint `/uploads`.
Discord user Muppet requested that uploads be available outside of authelia when configured.
https://discord.com/channels/853755447970758686/944260106852368384/1095130701524914226
> [thelounge] Enable access to uploads

- roles/tauticord/defaults/main.yml
- roles/tauticord/tasks/main.yml
- sandbox.yml
Requries configuration via `config/config.yaml`
https://github.com/nwithan8/tauticord
Will update docs if merged.
Tested on my server with my Plex server.
> Add Tauticord Role

- roles/code_server/defaults/main.yml
As discussed in #sandbox-dev, the default bind mounts inside the container for the code-server role are currently wrong, this PR corrects them.
`/home/code-server/[...]` paths have been renamed to `/home/coder/[...]` while the `.local` one has been removed since it's not mentioned in the [official docs](https://coder.com/docs/code-server/latest/install#docker).
Untested.
> fix(code-server): mount the correct folders inside the container

- roles/komga/defaults/main.yml
[Komga has changed their default port from 8080 to 25600](https://komga.org/installation/upgrade.html), to make sure there aren't any issues we can either change the docker port, like I've done here, or pre-create a config specifying the 8080 server port and move it to /opt/komga. 
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.
> Change Komga docker port to the new Komga default.

- roles/discoflix/defaults/main.yml
- roles/discoflix/tasks/main.yml
- sandbox.yml
DiscoFlix is not only a Discord request bot that interfaces with Radarr & Sonarr, it's also a user management system, a REST API/DB, and a sleek WebUI - all of which run great with Sandbox.
For now, there are no default configurations provided to the DiscoFlix app upon install. Here is an example of how you would config for Radarr and Sonarr in Saltbox: 
Github: https://github.com/nickheyer/DiscoFlix
Docker Hub URL: https://hub.docker.com/repository/docker/nickheyer/discoflix
Docker Image: nickheyer/discoflix
These changes were tested on two machines:
1. A media server running saltbox that is currently in use
2. A second machine that I have setup for development
Currently unit/integration testing is not implemented for DiscoFlix, however I have a range of manual tests that I perform on …
> Add Role: Discoflix

- defaults/settings.yml.default
- roles/membarr/defaults/main.yml
- roles/membarr/tasks/main.yml
- roles/membarr/tasks/subtasks/settings.yml
- roles/membarr/templates/config.ini.j2
Will create docs for it if it gets that far. I was hoping someone could give this a once over, as I'm struggling to figure out if I'm doing something wrong or if the bot/role itself is the problem. 
I've tested it on my home server and my feederbox. It connects fine to discord and the bot works and responds well. Everything looks good there. Only issue is it doesn't seem to want to connect to plex and I need someone or a few people to test it for me maybe? Thanks!
> Add role: Membarr

- roles/handbrake/tasks/main.yml
Already performed in the included `set_docker_devices_variable.yml`
> cleanup(handbrake): remove redundant task

- roles/firefox/defaults/main.yml
Removed after realizing it's not necessary for VNC access.
> fix(firefox): remove pointless port binding

- roles/forgejo/defaults/main.yml
- roles/forgejo/tasks/main.yml
- sandbox.yml
Forgejo is a fork of Gitea that was created after name Gitea was taken over by Gitea Ltd, the for profit company now behind Gitea.
- Homepage: https://forgejo.org/
- Git repo: https://codeberg.org/forgejo/forgejo
_Please note that the Codeberg container registry does not have a `latest` tag, so I have pinned the latest version (`1.19.3-0`)._
> feat(role): add Foregejo

- roles/factorio/defaults/main.yml
- roles/factorio/tasks/main.yml
- sandbox.yml
Adds a a role to deploy a Factorio headless server. Will boot a fresh game with files at `/opt/factorio` if that folder is empty, otherwise will load the save if there is one. Additional configuration through `server-settings.json` as per the Factorio headless server [documentation](https://wiki.factorio.com/Multiplayer). 
[Docker image](https://hub.docker.com/r/goofball222/factorio).
Will try to make documentation soon.
> feat(role): add factorio

- roles/watchstate/defaults/main.yml
- roles/watchstate/tasks/main.yml
- roles/watchstate/tasks/main2.yml
- sandbox.yml
- https://github.com/ArabCoders/watchstate
- DNS for webhooks only, so Authelia disabled.
> feat(role): add watchstate

- roles/homepage/defaults/main.yml
As per the following link the below changes have been made 
https://gethomepage.dev/v0.7.2/more/homepage-move/
`image: ghcr.io/benphelps/homepage:latest to image: ghcr.io/gethomepage/homepage:latest.`
> Update homepage image URL

- roles/immich/defaults/main.yml
- roles/immich/tasks/main.yml
- sandbox.yml
Immich is a self hosted photo and video backup solution, and allows for a decent amount of customization. 
https://immich.app/docs/overview/introduction
https://github.com/imagegenius/docker-immich
https://github.com/immich-app/immich
I will make a doc page with some basic info on Immich.
I've tested this on 2 different servers so far. I'll attempt to get more people to give it a whirl as much as I can.
> Add-Immich

- roles/lgsm/defaults/main.yml
- roles/lgsm/tasks/main.yml
- roles/lgsm/tasks/main2.yml
- sandbox.yml
- scripts/check_missing_entries.sh
Role to install game servers using [docker-gameserver](https://github.com/GameServerManagers/docker-gameserver) to manage the servers. It depends on using the multi-instance configuration to set the correct image, directory, ports, and any other settings. 
The `lgsm` instance will be ignored since it will throw errors saying there is no such docker image. 
These are the instances i used to test in my inventory config
```yml
lgsm_instances: ["lgsm","lgsm_valheim", "lgsm_rust"]
lgsm_valheim_docker_image_tag: "vh"
lgsm_valheim_docker_ports_defaults: ["2456:2456/udp","2457:2457/udp"]
lgsm_rust_docker_ports_defaults: ["28015:28015/udp","28017:28017/udp","28082:28082/udp"]
```
The configs for servers are in `/opt/CONTAINERNAME/config-lgsm/LGSMSERVERNAME/`
For example my valheim config would be …
> feat(role): LinuxGameServerManager

- roles/linkwarden/defaults/main.yml
- roles/linkwarden/tasks/main.yml
- sandbox.yml
Add LinkWarden role with default configs and tasks 
Introduce a new Ansible role for LinkWarden, setting up default
variables for Docker deployment, such as container name, image,
environment variables, and networks. Included tasks handle PostgreSQL dependency, DNS setup, container management, and directory creation. This addition allows for LinkWarden deployment and maintenance in the
Sandbox environment.
<3 GPT
Relevant issue: #324
> Add LinkWarden role

- roles/notifiarr/defaults/main.yml
The database corruption check requires a folder to move and then examine a backup file from the Starr apps which is /tmp by default it doesn't have access to that obviously so this will allow it to use its appdata folder for this purpose
I'm not sure if I did it entirely right I probably did not
https://notifiarr.wiki/en/Client/Configuration#tmp-not-found
> Notifiarr: Starr app Database Checks Requirement

- roles/notifiarr/defaults/main.yml
This adds privileged setting toggle that is required for the snapshot feature in Notifiarr which provides useful system and drive information such as SMART
> Notifiarr: Add privileged setting to support snapshots feature

- roles/barcodebuddy/defaults/main.yml
- roles/barcodebuddy/tasks/main.yml
- roles/grocy/defaults/main.yml
- roles/grocy/tasks/main.yml
- sandbox.yml
Grocy is a web-based self-hosted groceries & household management solution for your home.
Inventory and track your household consumables, from your pantry, to your fridge, to your cleaning supplies.
Also allows assigning and tracking of Household Chores.
(can also be connected with Home Assistant)
Recipes can also be added to Grocy and, in theory, this can simplify Meal Planning and creating Shopping Lists.
Companion tool for Grocy that makes adding/managing items easier.
Pass barcodes to Barcode Buddy.
If already in the Grocys system, it will consume/add/open the product there.
If an unknown barcode is passed, the product name will be looked up and a corresponding product can be chosen in the Web UI.
Tags can be saved — if a new product contains the tag in the name, the product will be …
> Add Grocy and Barcode Buddy

- roles/teslamate/defaults/main.yml
- roles/teslamate/tasks/main.yml
For existing roles;
The issue we were having was that two .ini's were generated and two fact sheets were made. I merged both facts into a singular sheet and created a single .ini to store it. I then added a tag in tasks that allows the user to run sb install sandbox-teslamate-grafana to grab the DB password the user needs when setting up the data source in grafana.
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.
> Teslamate secrets fix

- roles/fireflyiii_importer/defaults/main.yml
- roles/fireflyiii_importer/tasks/main.yml
This pull request fixes an issue with client ID authentication between fireflyiii and fireflyiii_importer. Currently the importer only relies on Token Access, which requires to add a value to localhost.yml inventory. I personnaly haven't been able to successfully use the importer relying on the Token Access method.
Currently when creating a Client ID in Firefly III (Profile > Oauth) using an URL including a `_` doesn't work and doesn't display any error message. Replacing it with `-` fixes this issue and allows you to use Client ID instead of an Access Token.
For firefly users please don't forget to remove old containers since the name changed.
> FireflyIII Importer: Change domain name to fireflyiii-importer

- roles/fireflyiii_importer/defaults/main.yml
This pull request allows user to import CSV files from the server.
By default, the importer allows users to import CSV using the web interface. This interface doesn't surface big CSV files because of a 600 seconds processing limitation. This limitation doesn't exists from the server side, procedure is explained in the following documentation: https://docs.firefly-iii.org/how-to/data-importer/import/automated/
Config and transactions files need to be copied in /opt/fireflyiii/import directory.
New functionalities:
- Added env variable IMPORT_DIR_ALLOWLIST=/import
- Added directory /opt/fireflyiii/import
- Added volume /opt/fireflyiii/import:/import.
> FireflyIII Importer: Adds support for server-side import

- roles/homebox/defaults/main.yml
- roles/homebox/tasks/main.yml
The [original Homebox project](https://github.com/hay-kot/homebox) appears to have been archived in June of 2024, but a [fork](https://github.com/sysadminsmedia/homebox) appears to be under active development. This PR is just a change of the image that the role uses.
I am not a Homebox power user by any means, so if there is specific Homebox functionality that should be tested please let me know. Additionally if there are any test steps you would have expected to see when moving a Sandbox role to a fork I'm happy to go through those as well.
> Homebox fork

- roles/wrapperr/defaults/main.yml
It looks like at some point there was an upstream change to the Wrapperr volume mapping with regards to the internal container path. A new install of the app would lose any configuration changes if the tag was run again.
The Wrapperr docker compose example from their [GitHub](https://github.com/aunefyren/wrapperr/wiki/Docker) has the volume mapping as `'./my-folder:/app/config'`, but the Sandbox role uses `"{{ wrapperr_paths_location }}:/var/www/html/config"`. This PR updates the mapping to what is currently expected by Wrapperr.
```
wrapperr_docker_volumes_default:
- "{{ wrapperr_paths_location }}:/app/config"
```
I'd appreciate it if a reviewer did a sanity check and considered if this would break any other users existing Wrapper setups, I think that's a little over my head. Thanks!
> Update Wrapperr docker volume

- roles/yacht/defaults/main.yml
Add IMAGES, VOLUMES, and NETWORKS permissions to Yacht's Docker socket proxy configuration to fix 403 Forbidden errors when accessing Docker resources.
This change allows Yacht to properly access and display Docker images, volumes, and networks through the socket proxy, resolving the 403 Forbidden errors that were preventing full functionality of the Yacht container management UI.
> fix(yacht): add missing docker socket proxy permissions

- roles/homepage/files/bookmarks.yaml
- roles/homepage/files/services.yaml
- roles/homepage/files/widgets.yaml
- roles/homepage/templates/docker.yaml.j2
- roles/homepage/templates/settings.yaml.j2
Updating an existing role, noticed that the config files have embedded documentation URLs that were 404ing because Homepage devs changed the path on their docs site.
Base URL used to be https://gethomepage.dev/en/configs/, is now https://gethomepage.dev/configs/
These are just oneliner changes to the commented out URLs in each affected file.
Updated the URLs to reflect the pattern change and confirmed they all load when navigated to on my machine.
> Updating Homepage documentation URLs to correct location

- roles/plex_auto_languages/defaults/main.yml
Thanks to @JourneyOver we have a working fork of Plex-Auto-Languages.
[https://github.com/JourneyDocker/Plex-Auto-Languages](https://github.com/JourneyDocker/Plex-Auto-Languages)
I simply changed image and default tag according to the new fork.
I  tested the changes on my saltbox server. Updated the defaults,  installed with `sb install sandbox-plex-auto-languages`. Works fine.
- [ x] Tested
> Fix: Changed broken repo of Plex-Auto_languages to working and active fork

- roles/actualbudget/defaults/main.yml
Removed the colons that were causing duplicate directories being created at time of role install. When sb install sandbox-actualbudget is installed it creates: /opt/actualbudget
/opt/actualbudget:
because of the colons
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.
> Update actualbudget_paths_folders_list format

- roles/paperless_ngx/tasks/main.yml
Bump Paperless-NGX Gotenberg to 8.22 per paperless project's recommended/default compose
- https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml
- https://docs.paperless-ngx.com/changelog/#dependencies_1
Current sandbox compose file is pinned to 7.8, which is almost 2 years old.
- Overrode tasks/main.yml with 8.22 tag locally, and re-ran sb install sandbox-paperless-ngx
- Confirmed Gotenberg is running 8.22
- Confirmed web client starts and accepts new files
> Bump Paperless-NGX Gotenberg Version to 8.22
